# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/dependabot-2.0.json
version: 2
updates:
  - package-ecosystem: docker
    commit-message:
      prefix: "chore"
    directory: /
    schedule:
      interval: weekly
    target-branch: dev
  - package-ecosystem: github-actions
    commit-message:
      prefix: "chore"
    directory: /
    schedule:
      interval: weekly
    target-branch: dev
  # ! uv updates are broken https://github.com/cca/cca_invenio/actions
  # maybe because of the site folder?
  - package-ecosystem: "uv"
    commit-message:
      prefix: "chore"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: dev
